### ISSUE TITLE
Enabling dnssec fails

### ISSUE THREAD

**Issue by joe-bowman** [saltstack-formulas/bind-formula#100]
Due to an issue with nesting, you end up with two pillar IDs that are identical.

I believe this is due to the dnssec logic that this supposed to be inside the 'included' file, is actually outside that if block.

**Comment by joe-bowman** [comment]
Turns out this isn't a nesting issue, but just a duplicate ID (`signed-<zone>` and `signed-<view>-<zone>` are both declared, even though for the default view, the value of `<view>` is an empty string).

**Comment by aanriot** [comment]
Thanks @joe-bowman , I just commented #101 .
