### ISSUE TITLE
Enabling auto_serial on Debian fails; included file not found

### ISSUE THREAD

**Issue by joe-bowman** [saltstack-formulas/bind-formula#102]
The `directory` declaration in `named.conf.options` appears to be statically defined; even though `named_directory` is specified in the map; for most archs, the value in the map and in `named.conf.options` matches - but not for Debian.

As a result, when using `auto_serial`, the include file root is based from the `directory` declaration, and the file is located in `named_directory`.

The `named.conf.options` template should reference the `named_directory` variable from the map.

**Comment by aanriot** [comment]
Thanks @joe-bowman , I just commented #103.
