### ISSUE TITLE
Missing documentation in pillar.example

### ISSUE THREAD

**Issue by mjinks** [saltstack-formulas/bind-formula#32]
As written, "pillar.example" has four instances of "bind:" formatted to look like the base of a pillar entry.

Each one has distinct types of data, so this n00b took that to mean that Salt would condense the file into distinct pillar items without any trouble. Instead, the pillar doesn't compile at all, and the errors it throws didn't help (me at least) know what the reason was.

Proposal: Either remove all but the first "bind:" heading, or insert comments to explain how they should be used.

**Comment by gravyboat** [comment]
Hmm, I'm not sure why that was put in that way. @whiteinge It looks like originally you added the pillar where it's broken into multiple bind sections. Any specific reason you did that or can we fix it up?

**Comment by whiteinge** [comment]
They're meant to serve as examples different possible configurations.

:+1: for separating each with explanatory comments.

**Comment by gravyboat** [comment]
Awesome, thanks for weighing in @whiteinge.

**Comment by Aloz1** [comment]
+1 for adding comments to pillar.example.

It looks like no one's made any great strides regarding comments over the last year, so would it be fine if I had a crack at this?

**Comment by gravyboat** [comment]
@Aloz1 Go for it!
