### ISSUE TITLE
ipv6 / ipv4 as options

### ISSUE THREAD

**Issue by cybacolt** [saltstack-formulas/bind-formula#43]
i know bind9 accepts both by default, but should there be a way to also choose one or the other?

ipv6 lookups on our ipv4 network are making a mess of the logs and appear to be breaking ipv4 lookups. adding -4 to /etc/default/bind9 OPTIONS resolved this.

i've fixed this by creating my own state to manage /etc/default/bind9, but it seems more appropriate that it be handled by this formula...

**Comment by gravyboat** [comment]
I don't see any problem with adding that, it probably just wasn't an issue when that code was written. I don't like the idea of editing the `sysctl.conf` in the event it's managed by other files, but I feel like it wouldn't be a big deal to add this to the config.sls. We could add a couple pillar keys (`bind_ipv4`, `bind_ipv6`) then manage the file pretty easily. If both match (or neither) it will leave the file alone and just not create it, if one of them matches it can drop in the relevant code, then do a watch in `bind_restart`.

**Comment by cybacolt** [comment]
agreed, turning off either ipv4/ipv6 for the host is probably overreach.

might have a go at this.

**Comment by gravyboat** [comment]
Closing this as the PR is merged, thanks!
