### ISSUE TITLE
pillar.example extra semicolon

### ISSUE THREAD

**Issue by mavhc** [saltstack-formulas/bind-formula#52]
allow-recursion: '{ any; };'  # Never include this on a public resolver

https://github.com/saltstack-formulas/bind-formula/blob/master/pillar.example#L14

The semicolon after the close brace seems to cause an error when bind starts as the file is compiled to have two semicolons in a  row

**Comment by gravyboat** [comment]
Does the rendered file look like `'{ any; };';`?

**Comment by ukretschmer** [comment]
Semicolons are automatically set after option statement in named.conf.options. @mavhc , just remove the last semicolon in your pillar data and it will generate the correct config file.

 The pillar.example should be corrected to:

`allow-recursion: '{ any; }'  # Never include this on a public resolver`
