### ISSUE TITLE
How do I override map.jinja values?

### ISSUE THREAD

**Issue by Routhinator** [saltstack-formulas/bind-formula#60]
I currently cannot get this module to see the zones_source_dir on RedHat (CentOS) because it is configured with a leading slash. If I edit the module source and remove the leading slash I can get it to deploy a file from "/srv/salt/base/srv/salt/zones/", which is quite ugly. 

I want to override this variable to be exactly as it is on Arch, "zones" 

This is a saner default, this way I can present a file in /srv/salt/base/zones/ and it will find it.

**Comment by gravyboat** [comment]
Map values are merged with the pillar: https://github.com/saltstack-formulas/bind-formula/blob/master/bind/map.jinja#L55, you can overwrite them in the lookup portion: https://github.com/saltstack-formulas/bind-formula/blob/master/pillar.example#L2

**Comment by 0xf10e** [comment]
Like @gravyboat says, you can overwrite thos with `pillar[bind:lookup]`:
```
@dns-dhcp:/srv/salt/pillar.git$ sudo salt-call pillar.items bind:lookup
[INFO    ] Determining pillar cache
local:
    ----------
    bind:lookup:
        ----------
        zones_source_dir:
            my_zone_data_dir
```

```
@dns-dhcp:/srv/salt/pillar.git$ sudo salt-call state.sls bind.config
[INFO    ] Determining pillar cache
[INFO    ] Loading fresh modules for state activity
[...]
----------
          ID: zones-salt.example.org
    Function: file.managed
        Name: /var/cache/bind/zones/db.example.org
      Result: False
     Comment: Source file salt://my_zone_data_dir/db.example.org not found
     Started: 19:05:55.262461
    Duration: 1.048 ms
     Changes:   
----------
[...]
```

But I agree, the default is broken.
