### ISSUE TITLE
Allow for configuration of in-line signing for zones

### ISSUE THREAD

**Issue by davidkarlsen** [saltstack-formulas/bind-formula#64]
See https://deepthought.isc.org/article/AA-00711/0/In-line-Signing-With-NSEC3-in-BIND-9.9-A-Walk-through.html for a walkthrough.

**Comment by davidkarlsen** [comment]
I added this in my fork: https://github.com/davidkarlsen/bind-formula/commit/28c6c29924cf17c5e88d84c0dda3ab068749ff60 - but our two repos have drifted a bit since then - if there is interest for this I can attempt to reintegrate master and open a PR?

**Comment by javierbertoli** [comment]
Hi @davidkarlsen, are you still interested in submitting a PR for this?

**Comment by davidkarlsen** [comment]
Hi. No longer I moved forward to ansible.

**Comment by javierbertoli** [comment]
Closed vía #98
