### ISSUE TITLE
configured_zones vs available_zones?

### ISSUE THREAD

**Issue by darkpixel** [saltstack-formulas/bind-formula#72]
Looking here:

https://github.com/saltstack-formulas/bind-formula/blob/master/bind/config.sls#L133

You are generating a list of zones from configured_zones, but then require available_zones to contain a zone name with a 'file' key.  Why are there two authoritative sources for creating a zone?  Why couldn't configured_zones simply contain a 'file' key so you don't have to duplicate zone definitions in two places in pillar data?  Am I missing something?

**Comment by ppieprzycki** [comment]
Hi what I'm seeing this is useful when you using views. You define zone with all data and options once under available_zones. Then this zone can be used multiple times.
