### ISSUE TITLE
LDAP backend

### ISSUE THREAD

**Issue by tobiasBora** [saltstack-formulas/bind-formula#86]
Hello,

Thank you for this formula. I'd like to use LDAP as a backend for bind, but I can't find any option here, did I miss something?

The generated configuration would looks like:
```
// A standard zone
zone "deimos.fr" {
        type master;
        database "ldap ldap://127.0.0.1/ou=deimos.fr,ou=dns,o=deimos,dc=fr???? \
        !bindname=cn=dnsadmin%2cou=dns%2co=deimos%2cdc=fr,!x-bindpw=DnsPassword 172800";
        notify yes;
};
 
// A reverse zone
zone "1.168.192.in-addr.arpa" {
        type master;
        database "ldap ldap://127.0.0.1/ou=1.168.192.in-addr.arpa,ou=dns,o=deimos,dc=fr???? \
        !bindname=cn=dnsadmin%2cou=dns%2co=deimos%2cdc=fr,!x-bindpw=DnsPassword 172800";
        notify yes;
};
```

Thank you!

Source: [https://wiki.deimos.fr/Mise_en_place_d%27un_serveur_Bind_en_backend_LDAP](https://wiki.deimos.fr/Mise_en_place_d%27un_serveur_Bind_en_backend_LDAP)

**Comment by aanriot** [comment]
@tobiasBora At the moment, it seems to be unsupported, indeed, but you may want to add more options to `named.conf.local.jinja`.

**Comment by aanriot** [comment]
Are you expecting to write a merge request @tobiasBora? Any other people interested by LDAP support around?

**Comment by aanriot** [comment]
Any news @tobiasBora ?

**Comment by aanriot** [comment]
Timeout.
